import numpy as np

dirdic = {\
"dir": "result"\
}

plotdir = {\
"dir": "plots"\
}

configfile: "snakeconfig.yaml" # snakeconfig.yaml contains fixed parameters

paramsdic = {\
    # "obs_iteration": {\
    #     "obs_iteration": np.array([2,4,5,10,20,30,50]),\
    #     "dt":            np.array([0.1]),\
    #     "duration":      np.array([35.]),\
    #     "replicates":    np.array([10])\
    #     },\
    # "duration": {\
    #     "obs_iteration": np.array([5]),\
    #     "dt":            np.array([0.1]),\
    #     "duration":      np.around(np.arange(60.,361.,60.), decimals=1),\
    #     "replicates":    np.array([10])\
    #     },\
    "replicates": {\
        "obs_iteration": np.array([5]),\
        "dt":            np.array([0.25]),\
        "duration":      np.array([35.]),\
        "replicates":    pow(2, np.arange(9,14,1))\
    }
}

arrayparam = {\
"iter":    np.arange(1,101,1)\
}

variables = ["log[STAT]0", "log[pSTAT]0", "log[pSTAT-pSTAT]0", "log[npSTAT-npSTAT]0", "log[nSTAT1]0", "log[nSTAT2]0", "log[nSTAT3]0", "log[nSTAT4]0", "log[nSTAT5]0", "logp1", "logp2", "logp3", "logp4", "logu1", "logu2", "logu3", "logu4", "logu5", "Opstat", "Otstat", "Ststat"]

include: "../../util/snakerules_jakstat"

rule linuxbuild:
    params:
        mem="4G"
    input:
        "model.jl",
        "twin_experiment.jl",
        "../../src/AdjointBackwardObsparam.jl",
        "../../src/types_backward_spline_obsparams3.jl",
        "../../src/adjoint_backward_spline_obsparam.jl",
        "../../src/assimilate_backward_obsparam2.jl",
        "../../util/check_args.jl",
        "../../util/experiment_ccompile_backward_obsparam.jl"
    output:
        'builddir/twin_experiment',
        'builddir/twin_experiment.so',
        'builddir/twin_experiment.o'
    shell:
        "julia ~/.julia/v0.6/PackageCompiler/juliac.jl -vae twin_experiment.jl"

rule macbuild:
    input:
        "model.jl",
        "twin_experiment.jl",
        "../../src/AdjointBackwardObsparam.jl",
        "../../src/types_backward_spline_obsparams3.jl",
        "../../src/adjoint_backward_spline_obsparam.jl",
        "../../src/assimilate_backward_obsparam2.jl",
        "../../util/check_args.jl",
        "../../util/experiment_ccompile_backward_obsparam.jl"
    output:
        'builddir/twin_experiment',
        'builddir/twin_experiment.dylib',
        'builddir/twin_experiment.o'
    shell:
        "julia /Applications/JuliaPro-0.6.2.2.app/Contents/Resources/pkgs-0.6.2.2/v0.6/PackageCompiler/juliac.jl -vae twin_experiment.jl"
