import numpy as np

dirdic = {\
"dir": "result"\
}

plotdir = {\
"dir": "plots"\
}

configfile: "snakeconfig.yaml" # snakeconfig.yaml contains fixed parameters

paramsdic = {\
    "obs_variance": {\
        "obs_variance":  pow(2., np.arange(-15,-5,1)),\
        "obs_iteration": np.array([5]),\
        "dt":            np.array([0.01]),\
        "duration":      np.array([10.]),\
        "replicates":    np.array([1])\
        },\
    "obs_iteration": {\
        "obs_variance":  np.array([pow(2, -13)]),\
        "obs_iteration": np.array([1,2,10,20,50,100]),\
        "dt":            np.array([0.01]),\
        "duration":      np.array([10.]),\
        "replicates":    np.array([1])\
        },\
    "duration": {\
        "obs_variance":  np.array([pow(2, -13)]),\
        "obs_iteration": np.array([5]),\
        "dt":            np.array([0.01]),\
        "duration":      np.around(np.arange(1.,10.,1.), decimals=1),\
        "replicates":    np.array([1])\
        },\
    "replicates": {\
        "obs_variance":  np.array([1.]),\
        "obs_iteration": np.array([5]),\
        "dt":            np.array([0.01]),\
        "duration":      np.array([10.]),\
        "replicates":    pow(2, np.arange(1,5,1))\
        }\
}

arrayparam = {\
"iter":    np.arange(1,101,1)\
}

variables = ["x", "m", "k1", "Km1", "Vmax1", "k2", "Km2", "Vmax2"]

include: "../../util/snakerules"

rule linuxbuild:
    params:
        mem="4G"
    input:
        'michaelis.jl',
        '../../util/experiment_ccompile.jl',
        '../../util/check_args.jl',
        '../../util/optparser.jl',
        '../../src/Adjoints.jl',
        '../../src/types.jl',
        '../../src/adjoint.jl',
        '../../src/assimilate.jl'
    output:
        'builddir/michaelis',
        'builddir/michaelis.so',
        'builddir/michaelis.o'
    shell:
        "julia ~/.julia/v0.6/PackageCompiler/juliac.jl -vae michaelis.jl"

rule macbuild:
    input:
        'michaelis.jl',
        '../../util/experiment_ccompile.jl',
        '../../util/check_args.jl',
        '../../util/optparser.jl',
        '../../src/Adjoints.jl',
        '../../src/types.jl',
        '../../src/adjoint.jl',
        '../../src/assimilate.jl'
    output:
        'builddir/michaelis',
        'builddir/michaelis.dylib',
        'builddir/michaelis.o'
    shell:
        "julia /Applications/JuliaPro-0.6.2.2.app/Contents/Resources/pkgs-0.6.2.2/v0.6/PackageCompiler/juliac.jl -vae michaelis.jl"
